// @generated by scripts/generate-registries.mjs. Do not edit manually.

export type {
  ComponentListItem,
  ComponentsAddInput,
  ComponentsAddResult,
  ComponentsGetQuery,
  ComponentsGetResult,
  ComponentsListQuery,
  ComponentsListResult,
  ComponentsRemoveInput,
  ComponentsRemoveResult,
  ComponentsUpdateInput,
  ComponentsUpdateResult,
} from './component/contract.ts'
export type {
  DomainReloadResult,
} from './domain/contract.ts'
export type {
  EditorStateResult,
} from './editor/contract.ts'
export type {
  ExecuteResult,
} from './execute/contract.ts'
export type {
  CreateTransform,
  GameObjectCreateInput,
  GameObjectCreateResult,
  GameObjectDestroyInput,
  GameObjectDestroyResult,
  GameObjectDimension,
  GameObjectFindItem,
  GameObjectFindQuery,
  GameObjectFindResult,
  GameObjectGetInput,
  GameObjectGetResult,
  GameObjectReparentInput,
  GameObjectReparentResult,
  GameObjectUpdateInput,
  GameObjectUpdateResult,
  PrimitiveTypeName,
  TransformSpace,
  Vector3Value,
} from './gameobject/contract.ts'
export type {
  LayerItem,
  LayersAddInput,
  LayersAddResult,
  LayersGetQuery,
  LayersGetResult,
  LayersRemoveInput,
  LayersRemoveResult,
} from './layer/contract.ts'
export type {
  LogEntry,
  LogsQuery,
  LogsResult,
  LogsSeverity,
} from './log/contract.ts'
export type {
  MaterialAssignInput,
  MaterialAssignResult,
  MaterialColor,
  MaterialCreateInput,
  MaterialCreateResult,
  MaterialGetInput,
  MaterialGetResult,
  MaterialPropertiesGetInput,
  MaterialPropertiesGetResult,
  MaterialPropertiesSetInput,
  MaterialPropertiesSetResult,
  MaterialPropertyGetValue,
  MaterialPropertySetValue,
  MaterialPropertyType,
  MaterialSummary,
  MaterialVector,
} from './material/contract.ts'
export type {
  PackageItem,
  PackagesAddInput,
  PackagesAddResult,
  PackagesGetQuery,
  PackagesGetResult,
  PackagesRemoveInput,
  PackagesRemoveResult,
} from './package/contract.ts'
export type {
  CreateTransform as PrefabCreateTransform,
  PrefabInstantiateInput,
  PrefabInstantiateResult,
  PrefabSaveInput,
  PrefabSaveResult,
  TransformSpace as PrefabTransformSpace,
  Vector3Value as PrefabVector3Value,
} from './prefab/contract.ts'
export type {
  SceneActiveResult,
  SceneCreateResult,
  SceneHierarchyNode,
  SceneHierarchyQuery,
  SceneHierarchyResult,
  SceneInfo,
  SceneListItem,
  SceneListQuery,
  SceneListResult,
  SceneOpenResult,
} from './scene/contract.ts'
export type {
  ScriptableObjectCreateInput,
  ScriptableObjectCreateResult,
  ScriptableObjectGetInput,
  ScriptableObjectGetResult,
  ScriptableObjectSummary,
  ScriptableObjectUpdateInput,
  ScriptableObjectUpdateResult,
} from './scriptableobject/contract.ts'
export type {
  SettingsResult,
  SettingsUpdateInput,
} from './settings/contract.ts'
export type {
  StatusResult,
} from './status/contract.ts'
export type {
  TagItem,
  TagsAddInput,
  TagsAddResult,
  TagsGetQuery,
  TagsGetResult,
  TagsRemoveInput,
  TagsRemoveResult,
} from './tag/contract.ts'
export type {
  TestListItem,
  TestListQuery,
  TestListResult,
  TestMode,
  TestRunItem,
  TestRunQuery,
  TestRunResult,
  TestStatus,
} from './test/contract.ts'
