import { componentsAddCommand, componentsGetCommand, componentsListCommand, componentsRemoveCommand, componentsUpdateCommand } from './component/contract.ts'
import { domainReloadCommand } from './domain/contract.ts'
import { editorPauseCommand, editorPlayCommand, editorStopCommand } from './editor/contract.ts'
import { executeCommand } from './execute/contract.ts'
import { gameObjectCreateCommand, gameObjectDestroyCommand, gameObjectFindCommand, gameObjectGetCommand, gameObjectReparentCommand, gameObjectUpdateCommand } from './gameobject/contract.ts'
import { layersAddCommand, layersGetCommand, layersRemoveCommand } from './layer/contract.ts'
import { logsCommand } from './log/contract.ts'
import { materialAssignCommand, materialCreateCommand, materialGetCommand } from './material/contract.ts'
import { packagesAddCommand, packagesGetCommand, packagesRemoveCommand } from './package/contract.ts'
import { prefabInstantiateCommand, prefabSaveCommand } from './prefab/contract.ts'
import { sceneActiveCommand, sceneCreateCommand, sceneHierarchyCommand, sceneListCommand, sceneOpenCommand } from './scene/contract.ts'
import { settingsGetCommand, settingsUpdateCommand } from './settings/contract.ts'
import { scriptableObjectCreateCommand, scriptableObjectGetCommand, scriptableObjectUpdateCommand } from './scriptableobject/contract.ts'
import { statusCommand } from './status/contract.ts'
import { tagsAddCommand, tagsGetCommand, tagsRemoveCommand } from './tag/contract.ts'
import { testListCommand, testRunCommand } from './test/contract.ts'

export const allCommands = [componentsListCommand, componentsAddCommand, componentsGetCommand, componentsRemoveCommand, componentsUpdateCommand, domainReloadCommand, editorPlayCommand, editorPauseCommand, editorStopCommand, executeCommand, gameObjectCreateCommand, gameObjectDestroyCommand, gameObjectUpdateCommand, gameObjectReparentCommand, gameObjectGetCommand, gameObjectFindCommand, layersGetCommand, layersAddCommand, layersRemoveCommand, logsCommand, materialCreateCommand, materialGetCommand, materialAssignCommand, packagesGetCommand, packagesAddCommand, packagesRemoveCommand, prefabInstantiateCommand, prefabSaveCommand, statusCommand, settingsGetCommand, settingsUpdateCommand, sceneListCommand, sceneHierarchyCommand, sceneActiveCommand, sceneCreateCommand, sceneOpenCommand, scriptableObjectCreateCommand, scriptableObjectGetCommand, scriptableObjectUpdateCommand, tagsGetCommand, tagsAddCommand, tagsRemoveCommand, testListCommand, testRunCommand] as const
